import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  balance: 0,
  expenses: [
    // ===== СІЧЕНЬ =====
    {
      id: 1001,
      date: "2026-01-01",
      description: "—",
      category: { label: "Транспорт", value: "transport" },
      sum: "1200",
    },
    {
      id: 1002,
      date: "2026-01-01",
      description: "—",
      category: { label: "Продукти", value: "products" },
      sum: "6200",
    },
    {
      id: 1003,
      date: "2026-01-01",
      description: "—",
      category: { label: "Здоров’я", value: "health" },
      sum: "900",
    },
    {
      id: 1004,
      date: "2026-01-01",
      description: "—",
      category: { label: "Алкоголь", value: "alcohol" },
      sum: "700",
    },
    {
      id: 1005,
      date: "2026-01-01",
      description: "—",
      category: { label: "Розваги", value: "fun" },
      sum: "1500",
    },
    {
      id: 1006,
      date: "2026-01-01",
      description: "—",
      category: { label: "Все для дому", value: "home" },
      sum: "1100",
    },
    {
      id: 1007,
      date: "2026-01-01",
      description: "—",
      category: { label: "Техніка", value: "tech" },
      sum: "3200",
    },
    {
      id: 1008,
      date: "2026-01-01",
      description: "—",
      category: { label: "Комуналка, зв’язок", value: "utilities" },
      sum: "2800",
    },
    {
      id: 1009,
      date: "2026-01-01",
      description: "—",
      category: { label: "Спорт, хобі", value: "sport" },
      sum: "900",
    },
    {
      id: 1010,
      date: "2026-01-01",
      description: "—",
      category: { label: "Навчання", value: "education" },
      sum: "1400",
    },
    {
      id: 1011,
      date: "2026-01-01",
      description: "—",
      category: { label: "Інше", value: "other" },
      sum: "600",
    },

    // ===== ЛЮТИЙ =====
    {
      id: 1101,
      date: "2026-02-01",
      description: "—",
      category: { label: "Транспорт", value: "transport" },
      sum: "1100",
    },
    {
      id: 1102,
      date: "2026-02-01",
      description: "—",
      category: { label: "Продукти", value: "products" },
      sum: "5800",
    },
    {
      id: 1103,
      date: "2026-02-01",
      description: "—",
      category: { label: "Здоров’я", value: "health" },
      sum: "700",
    },
    {
      id: 1104,
      date: "2026-02-01",
      description: "—",
      category: { label: "Алкоголь", value: "alcohol" },
      sum: "500",
    },
    {
      id: 1105,
      date: "2026-02-01",
      description: "—",
      category: { label: "Розваги", value: "fun" },
      sum: "1300",
    },
    {
      id: 1106,
      date: "2026-02-01",
      description: "—",
      category: { label: "Все для дому", value: "home" },
      sum: "900",
    },
    {
      id: 1107,
      date: "2026-02-01",
      description: "—",
      category: { label: "Техніка", value: "tech" },
      sum: "0",
    },
    {
      id: 1108,
      date: "2026-02-01",
      description: "—",
      category: { label: "Комуналка, зв’язок", value: "utilities" },
      sum: "2600",
    },
    {
      id: 1109,
      date: "2026-02-01",
      description: "—",
      category: { label: "Спорт, хобі", value: "sport" },
      sum: "800",
    },
    {
      id: 1110,
      date: "2026-02-01",
      description: "—",
      category: { label: "Навчання", value: "education" },
      sum: "1200",
    },
    {
      id: 1111,
      date: "2026-02-01",
      description: "—",
      category: { label: "Інше", value: "other" },
      sum: "400",
    },

    // ===== БЕРЕЗЕНЬ =====
    {
      id: 1201,
      date: "2026-03-01",
      description: "—",
      category: { label: "Транспорт", value: "transport" },
      sum: "1300",
    },
    {
      id: 1202,
      date: "2026-03-01",
      description: "—",
      category: { label: "Продукти", value: "products" },
      sum: "6500",
    },
    {
      id: 1203,
      date: "2026-03-01",
      description: "—",
      category: { label: "Здоров’я", value: "health" },
      sum: "1200",
    },
    {
      id: 1204,
      date: "2026-03-01",
      description: "—",
      category: { label: "Алкоголь", value: "alcohol" },
      sum: "600",
    },
    {
      id: 1205,
      date: "2026-03-01",
      description: "—",
      category: { label: "Розваги", value: "fun" },
      sum: "1700",
    },
    {
      id: 1206,
      date: "2026-03-01",
      description: "—",
      category: { label: "Все для дому", value: "home" },
      sum: "1500",
    },
    {
      id: 1207,
      date: "2026-03-01",
      description: "—",
      category: { label: "Техніка", value: "tech" },
      sum: "2200",
    },
    {
      id: 1208,
      date: "2026-03-01",
      description: "—",
      category: { label: "Комуналка, зв’язок", value: "utilities" },
      sum: "2500",
    },
    {
      id: 1209,
      date: "2026-03-01",
      description: "—",
      category: { label: "Спорт, хобі", value: "sport" },
      sum: "1000",
    },
    {
      id: 1210,
      date: "2026-03-01",
      description: "—",
      category: { label: "Навчання", value: "education" },
      sum: "1600",
    },
    {
      id: 1211,
      date: "2026-03-01",
      description: "—",
      category: { label: "Інше", value: "other" },
      sum: "500",
    },

    // ===== КВІТЕНЬ =====
    {
      id: 1301,
      date: "2026-04-01",
      description: "—",
      category: { label: "Транспорт", value: "transport" },
      sum: "1200",
    },
    {
      id: 1302,
      date: "2026-04-01",
      description: "—",
      category: { label: "Продукти", value: "products" },
      sum: "6000",
    },
    {
      id: 1303,
      date: "2026-04-01",
      description: "—",
      category: { label: "Здоров’я", value: "health" },
      sum: "800",
    },
    {
      id: 1304,
      date: "2026-04-01",
      description: "—",
      category: { label: "Алкоголь", value: "alcohol" },
      sum: "400",
    },
    {
      id: 1305,
      date: "2026-04-01",
      description: "—",
      category: { label: "Розваги", value: "fun" },
      sum: "1400",
    },
    {
      id: 1306,
      date: "2026-04-01",
      description: "—",
      category: { label: "Все для дому", value: "home" },
      sum: "1000",
    },
    {
      id: 1307,
      date: "2026-04-01",
      description: "—",
      category: { label: "Техніка", value: "tech" },
      sum: "0",
    },
    {
      id: 1308,
      date: "2026-04-01",
      description: "—",
      category: { label: "Комуналка, зв’язок", value: "utilities" },
      sum: "2400",
    },
    {
      id: 1309,
      date: "2026-04-01",
      description: "—",
      category: { label: "Спорт, хобі", value: "sport" },
      sum: "900",
    },
    {
      id: 1310,
      date: "2026-04-01",
      description: "—",
      category: { label: "Навчання", value: "education" },
      sum: "1300",
    },
    {
      id: 1311,
      date: "2026-04-01",
      description: "—",
      category: { label: "Інше", value: "other" },
      sum: "450",
    },

    // ===== ТРАВЕНЬ =====
    {
      id: 1401,
      date: "2026-05-01",
      description: "—",
      category: { label: "Транспорт", value: "transport" },
      sum: "1300",
    },
    {
      id: 1402,
      date: "2026-05-01",
      description: "—",
      category: { label: "Продукти", value: "products" },
      sum: "6700",
    },
    {
      id: 1403,
      date: "2026-05-01",
      description: "—",
      category: { label: "Здоров’я", value: "health" },
      sum: "900",
    },
    {
      id: 1404,
      date: "2026-05-01",
      description: "—",
      category: { label: "Алкоголь", value: "alcohol" },
      sum: "500",
    },
    {
      id: 1405,
      date: "2026-05-01",
      description: "—",
      category: { label: "Розваги", value: "fun" },
      sum: "1600",
    },
    {
      id: 1406,
      date: "2026-05-01",
      description: "—",
      category: { label: "Все для дому", value: "home" },
      sum: "1200",
    },
    {
      id: 1407,
      date: "2026-05-01",
      description: "—",
      category: { label: "Техніка", value: "tech" },
      sum: "1500",
    },
    {
      id: 1408,
      date: "2026-05-01",
      description: "—",
      category: { label: "Комуналка, зв’язок", value: "utilities" },
      sum: "2600",
    },
    {
      id: 1409,
      date: "2026-05-01",
      description: "—",
      category: { label: "Спорт, хобі", value: "sport" },
      sum: "1000",
    },
    {
      id: 1410,
      date: "2026-05-01",
      description: "—",
      category: { label: "Навчання", value: "education" },
      sum: "1500",
    },
    {
      id: 1411,
      date: "2026-05-01",
      description: "—",
      category: { label: "Інше", value: "other" },
      sum: "500",
    },

    // ===== ЧЕРВЕНЬ =====
    {
      id: 1501,
      date: "2026-06-01",
      description: "—",
      category: { label: "Транспорт", value: "transport" },
      sum: "1200",
    },
    {
      id: 1502,
      date: "2026-06-01",
      description: "—",
      category: { label: "Продукти", value: "products" },
      sum: "6500",
    },
    {
      id: 1503,
      date: "2026-06-01",
      description: "—",
      category: { label: "Здоров’я", value: "health" },
      sum: "800",
    },
    {
      id: 1504,
      date: "2026-06-01",
      description: "—",
      category: { label: "Алкоголь", value: "alcohol" },
      sum: "600",
    },
    {
      id: 1505,
      date: "2026-06-01",
      description: "—",
      category: { label: "Розваги", value: "fun" },
      sum: "1400",
    },
    {
      id: 1506,
      date: "2026-06-01",
      description: "—",
      category: { label: "Все для дому", value: "home" },
      sum: "1100",
    },
    {
      id: 1507,
      date: "2026-06-01",
      description: "—",
      category: { label: "Техніка", value: "tech" },
      sum: "2000",
    },
    {
      id: 1508,
      date: "2026-06-01",
      description: "—",
      category: { label: "Комуналка, зв’язок", value: "utilities" },
      sum: "2500",
    },
    {
      id: 1509,
      date: "2026-06-01",
      description: "—",
      category: { label: "Спорт, хобі", value: "sport" },
      sum: "900",
    },
    {
      id: 1510,
      date: "2026-06-01",
      description: "—",
      category: { label: "Навчання", value: "education" },
      sum: "1400",
    },
    {
      id: 1511,
      date: "2026-06-01",
      description: "—",
      category: { label: "Інше", value: "other" },
      sum: "450",
    },

    // ===== ЛИПЕНЬ =====
    {
      id: 1601,
      date: "2026-07-01",
      description: "—",
      category: { label: "Транспорт", value: "transport" },
      sum: "1300",
    },
    {
      id: 1602,
      date: "2026-07-01",
      description: "—",
      category: { label: "Продукти", value: "products" },
      sum: "6800",
    },
    {
      id: 1603,
      date: "2026-07-01",
      description: "—",
      category: { label: "Здоров’я", value: "health" },
      sum: "900",
    },
    {
      id: 1604,
      date: "2026-07-01",
      description: "—",
      category: { label: "Алкоголь", value: "alcohol" },
      sum: "500",
    },
    {
      id: 1605,
      date: "2026-07-01",
      description: "—",
      category: { label: "Розваги", value: "fun" },
      sum: "1500",
    },
    {
      id: 1606,
      date: "2026-07-01",
      description: "—",
      category: { label: "Все для дому", value: "home" },
      sum: "1000",
    },
    {
      id: 1607,
      date: "2026-07-01",
      description: "—",
      category: { label: "Техніка", value: "tech" },
      sum: "2500",
    },
    {
      id: 1608,
      date: "2026-07-01",
      description: "—",
      category: { label: "Комуналка, зв’язок", value: "utilities" },
      sum: "2600",
    },
    {
      id: 1609,
      date: "2026-07-01",
      description: "—",
      category: { label: "Спорт, хобі", value: "sport" },
      sum: "1000",
    },
    {
      id: 1610,
      date: "2026-07-01",
      description: "—",
      category: { label: "Навчання", value: "education" },
      sum: "1500",
    },
    {
      id: 1611,
      date: "2026-07-01",
      description: "—",
      category: { label: "Інше", value: "other" },
      sum: "500",
    },

    // ===== СЕРПЕНЬ =====
    {
      id: 1701,
      date: "2026-08-01",
      description: "—",
      category: { label: "Транспорт", value: "transport" },
      sum: "1200",
    },
    {
      id: 1702,
      date: "2026-08-01",
      description: "—",
      category: { label: "Продукти", value: "products" },
      sum: "6400",
    },
    {
      id: 1703,
      date: "2026-08-01",
      description: "—",
      category: { label: "Здоров’я", value: "health" },
      sum: "800",
    },
    {
      id: 1704,
      date: "2026-08-01",
      description: "—",
      category: { label: "Алкоголь", value: "alcohol" },
      sum: "500",
    },
    {
      id: 1705,
      date: "2026-08-01",
      description: "—",
      category: { label: "Розваги", value: "fun" },
      sum: "1400",
    },
    {
      id: 1706,
      date: "2026-08-01",
      description: "—",
      category: { label: "Все для дому", value: "home" },
      sum: "1200",
    },
    {
      id: 1707,
      date: "2026-08-01",
      description: "—",
      category: { label: "Техніка", value: "tech" },
      sum: "2200",
    },
    {
      id: 1708,
      date: "2026-08-01",
      description: "—",
      category: { label: "Комуналка, зв’язок", value: "utilities" },
      sum: "2500",
    },
    {
      id: 1709,
      date: "2026-08-01",
      description: "—",
      category: { label: "Спорт, хобі", value: "sport" },
      sum: "900",
    },
    {
      id: 1710,
      date: "2026-08-01",
      description: "—",
      category: { label: "Навчання", value: "education" },
      sum: "1400",
    },
    {
      id: 1711,
      date: "2026-08-01",
      description: "—",
      category: { label: "Інше", value: "other" },
      sum: "450",
    },

    // ===== ВЕРЕСЕНЬ =====
    {
      id: 1801,
      date: "2026-09-01",
      description: "—",
      category: { label: "Транспорт", value: "transport" },
      sum: "1300",
    },
    {
      id: 1802,
      date: "2026-09-01",
      description: "—",
      category: { label: "Продукти", value: "products" },
      sum: "6700",
    },
    {
      id: 1803,
      date: "2026-09-01",
      description: "—",
      category: { label: "Здоров’я", value: "health" },
      sum: "900",
    },
    {
      id: 1804,
      date: "2026-09-01",
      description: "—",
      category: { label: "Алкоголь", value: "alcohol" },
      sum: "600",
    },
    {
      id: 1805,
      date: "2026-09-01",
      description: "—",
      category: { label: "Розваги", value: "fun" },
      sum: "1500",
    },
    {
      id: 1806,
      date: "2026-09-01",
      description: "—",
      category: { label: "Все для дому", value: "home" },
      sum: "1100",
    },
    {
      id: 1807,
      date: "2026-09-01",
      description: "—",
      category: { label: "Техніка", value: "tech" },
      sum: "2500",
    },
    {
      id: 1808,
      date: "2026-09-01",
      description: "—",
      category: { label: "Комуналка, зв’язок", value: "utilities" },
      sum: "2600",
    },
    {
      id: 1809,
      date: "2026-09-01",
      description: "—",
      category: { label: "Спорт, хобі", value: "sport" },
      sum: "1000",
    },
    {
      id: 1810,
      date: "2026-09-01",
      description: "—",
      category: { label: "Навчання", value: "education" },
      sum: "1500",
    },
    {
      id: 1811,
      date: "2026-09-01",
      description: "—",
      category: { label: "Інше", value: "other" },
      sum: "500",
    },

    // ===== ЖОВТЕНЬ =====
    {
      id: 1901,
      date: "2026-10-01",
      description: "—",
      category: { label: "Транспорт", value: "transport" },
      sum: "1200",
    },
    {
      id: 1902,
      date: "2026-10-01",
      description: "—",
      category: { label: "Продукти", value: "products" },
      sum: "6500",
    },
    {
      id: 1903,
      date: "2026-10-01",
      description: "—",
      category: { label: "Здоров’я", value: "health" },
      sum: "800",
    },
    {
      id: 1904,
      date: "2026-10-01",
      description: "—",
      category: { label: "Алкоголь", value: "alcohol" },
      sum: "500",
    },
    {
      id: 1905,
      date: "2026-10-01",
      description: "—",
      category: { label: "Розваги", value: "fun" },
      sum: "1400",
    },
    {
      id: 1906,
      date: "2026-10-01",
      description: "—",
      category: { label: "Все для дому", value: "home" },
      sum: "1100",
    },
    {
      id: 1907,
      date: "2026-10-01",
      description: "—",
      category: { label: "Техніка", value: "tech" },
      sum: "2200",
    },
    {
      id: 1908,
      date: "2026-10-01",
      description: "—",
      category: { label: "Комуналка, зв’язок", value: "utilities" },
      sum: "2500",
    },
    {
      id: 1909,
      date: "2026-10-01",
      description: "—",
      category: { label: "Спорт, хобі", value: "sport" },
      sum: "900",
    },
    {
      id: 1910,
      date: "2026-10-01",
      description: "—",
      category: { label: "Навчання", value: "education" },
      sum: "1400",
    },
    {
      id: 1911,
      date: "2026-10-01",
      description: "—",
      category: { label: "Інше", value: "other" },
      sum: "450",
    },

    // ===== ЛИСТОПАД =====
    {
      id: 2001,
      date: "2026-11-01",
      description: "—",
      category: { label: "Транспорт", value: "transport" },
      sum: "1300",
    },
    {
      id: 2002,
      date: "2026-11-01",
      description: "—",
      category: { label: "Продукти", value: "products" },
      sum: "6700",
    },
    {
      id: 2003,
      date: "2026-11-01",
      description: "—",
      category: { label: "Здоров’я", value: "health" },
      sum: "900",
    },
    {
      id: 2004,
      date: "2026-11-01",
      description: "—",
      category: { label: "Алкоголь", value: "alcohol" },
      sum: "500",
    },
    {
      id: 2005,
      date: "2026-11-01",
      description: "—",
      category: { label: "Розваги", value: "fun" },
      sum: "1600",
    },
    {
      id: 2006,
      date: "2026-11-01",
      description: "—",
      category: { label: "Все для дому", value: "home" },
      sum: "1100",
    },
    {
      id: 2007,
      date: "2026-11-01",
      description: "—",
      category: { label: "Техніка", value: "tech" },
      sum: "2000",
    },
    {
      id: 2008,
      date: "2026-11-01",
      description: "—",
      category: { label: "Комуналка, зв’язок", value: "utilities" },
      sum: "2600",
    },
    {
      id: 2009,
      date: "2026-11-01",
      description: "—",
      category: { label: "Спорт, хобі", value: "sport" },
      sum: "1000",
    },
    {
      id: 2010,
      date: "2026-11-01",
      description: "—",
      category: { label: "Навчання", value: "education" },
      sum: "1500",
    },
    {
      id: 2011,
      date: "2026-11-01",
      description: "—",
      category: { label: "Інше", value: "other" },
      sum: "500",
    },

    // ===== ГРУДЕНЬ =====
    {
      id: 2101,
      date: "2026-12-01",
      description: "—",
      category: { label: "Транспорт", value: "transport" },
      sum: "1400",
    },
    {
      id: 2102,
      date: "2026-12-01",
      description: "—",
      category: { label: "Продукти", value: "products" },
      sum: "7000",
    },
    {
      id: 2103,
      date: "2026-12-01",
      description: "—",
      category: { label: "Здоров’я", value: "health" },
      sum: "1000",
    },
    {
      id: 2104,
      date: "2026-12-01",
      description: "—",
      category: { label: "Алкоголь", value: "alcohol" },
      sum: "700",
    },
    {
      id: 2105,
      date: "2026-12-01",
      description: "—",
      category: { label: "Розваги", value: "fun" },
      sum: "1800",
    },
    {
      id: 2106,
      date: "2026-12-01",
      description: "—",
      category: { label: "Все для дому", value: "home" },
      sum: "1200",
    },
    {
      id: 2107,
      date: "2026-12-01",
      description: "—",
      category: { label: "Техніка", value: "tech" },
      sum: "2500",
    },
    {
      id: 2108,
      date: "2026-12-01",
      description: "—",
      category: { label: "Комуналка, зв’язок", value: "utilities" },
      sum: "2700",
    },
    {
      id: 2109,
      date: "2026-12-01",
      description: "—",
      category: { label: "Спорт, хобі", value: "sport" },
      sum: "1100",
    },
    {
      id: 2110,
      date: "2026-12-01",
      description: "—",
      category: { label: "Навчання", value: "education" },
      sum: "1600",
    },
    {
      id: 2111,
      date: "2026-12-01",
      description: "—",
      category: { label: "Інше", value: "other" },
      sum: "550",
    },
  ],
  incomes: [
    {
      id: 101,
      date: "2026-01-01",
      description: "Зарплата за січень",
      category: { label: "ЗП", value: "salary" },
      sum: "45000",
    },
    {
      id: 102,
      date: "2026-02-01",
      description: "Зарплата за лютий",
      category: { label: "ЗП", value: "salary" },
      sum: "47000",
    },
    {
      id: 103,
      date: "2026-03-01",
      description: "Зарплата за березень",
      category: { label: "ЗП", value: "salary" },
      sum: "50000",
    },
    {
      id: 104,
      date: "2026-04-01",
      description: "Зарплата за квітень",
      category: { label: "ЗП", value: "salary" },
      sum: "52000",
    },
    {
      id: 105,
      date: "2026-05-01",
      description: "Зарплата за травень",
      category: { label: "ЗП", value: "salary" },
      sum: "48000",
    },
    {
      id: 106,
      date: "2026-06-01",
      description: "Зарплата за червень",
      category: { label: "ЗП", value: "salary" },
      sum: "51000",
    },
    {
      id: 107,
      date: "2026-07-01",
      description: "Зарплата за липень",
      category: { label: "ЗП", value: "salary" },
      sum: "53000",
    },
    {
      id: 108,
      date: "2026-08-01",
      description: "Зарплата за серпень",
      category: { label: "ЗП", value: "salary" },
      sum: "55000",
    },
    {
      id: 109,
      date: "2026-09-01",
      description: "Зарплата за вересень",
      category: { label: "ЗП", value: "salary" },
      sum: "49000",
    },
    {
      id: 110,
      date: "2026-10-01",
      description: "Зарплата за жовтень",
      category: { label: "ЗП", value: "salary" },
      sum: "52000",
    },
    {
      id: 111,
      date: "2026-11-01",
      description: "Зарплата за листопад",
      category: { label: "ЗП", value: "salary" },
      sum: "60000",
    },
    {
      id: 112,
      date: "2026-12-01",
      description: "Зарплата за грудень",
      category: { label: "ЗП", value: "salary" },
      sum: "65000",
    },
  ],
};

const walletSlice = createSlice({
  name: "wallet",
  initialState,
  reducers: {
    addExpens(state, action) {
      state.expenses.push(action.payload);
    },
    deleteExpens(state, action) {
      state.expenses = state.expenses.filter(
        (expens) => expens.id !== action.payload,
      );
    },
    addIncome(state, action) {
      state.incomes.push(action.payload);
    },
    deleteIncome(state, action) {
      state.incomes = state.incomes.filter(
        (income) => income.id !== action.payload,
      );
    },
    addBalance(state, action) {
      state.balance = action.payload;
    },
    minusBalance(state, action) {
      state.balance -= action.payload;
    },
    plusBalance(state, action) {
      state.balance += action.payload;
    },
  },
});

export const WalletReducer = walletSlice.reducer;
export const {
  addExpens,
  deleteExpens,
  addIncome,
  deleteIncome,
  addBalance,
  minusBalance,
  plusBalance,
} = walletSlice.actions;
